[package]
name = "isomorphic"
version = "0.1.1"
edition = "2024"
authors = ["Wzh <wzh@uvwee.com>"]
description = "Getting a reference to an isomorphic type"
license = "MIT"
repository = "https://github.com/wzh19960613/lib_rust_isomorphic"

[features]
macros = []